### ISSUE TITLE
Shorten the file names and avoid using windows incompatible symbols in file names

### ISSUE THREAD

**Issue by coder-zs-cse** [greyhatguy007/Machine-Learning-Specialization-Coursera#10]
Many file names have the ':' inside which is not allowed in Windows and hence the repository is not getting cloned. 
Also many file names are really big which is why Windows is throwing an error while saving them, which is causing unecessary problems. Please shorten the file names and remove the semicolon from the file names.

**Comment by SalimovAlbert** [comment]
Had the same issues

**Comment by greyhatguy007** [comment]
Illegal file names for windows systems haa been fixed.
