### ISSUE TITLE
In C2W2 Optional Labs, there aren't any labs for the "Back Propagation" section in Andrew NG's course

### ISSUE THREAD

**Issue by ghost** [greyhatguy007/Machine-Learning-Specialization-Coursera#14]
**Describe the Error**
In ["C2W2 Optional labs" folder](https://github.com/greyhatguy007/Machine-Learning-Specialization-Coursera/tree/main/C2%20-%20Advanced%20Learning%20Algorithms/week2/optional-labs), there aren't any labs for the "Back Propagation" section in Andrew NG's Coursera course

**To Reproduce**
1. Go to [https://github.com/greyhatguy007/Machine-Learning-Specialization-Coursera/tree/main/C2%20-%20Advanced%20Learning%20Algorithms/week2/optional-labs](https://github.com/greyhatguy007/Machine-Learning-Specialization-Coursera/tree/main/C2%20-%20Advanced%20Learning%20Algorithms/week2/optional-labs)
3. Scroll down to the list of ipynb files
4. There aren't any labs for "Back Propagation"

**Expected behavior**
I expected two more optional labs, one about "Derivatives" and another about "Back propagation"

**Screenshots**
This is what was shown Andrew NG's Machine Learning Specialization course on Coursera
![image](https://user-images.githubusercontent.com/130979207/233044226-495c0dea-325c-4f38-ae9f-bfd2187eed1d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 112.0.5615.138 (Official Build) (64-bit)

**Additional context**
I'm just wondering if you forgot to add these "Derivatives" and "Back Propagation" optional labs. If this was intended, I apologize.

**Comment by greyhatguy007** [comment]
Will add it soon. 
Contributions are welcome.

**Comment by annoyingCode** [comment]
Actually, the course was updated a few months ago, and the back propagation was added in the update. This repository has all the contents before that update.

**Comment by greyhatguy007** [comment]
resolved in PR #30
