### ISSUE TITLE
Notation Tables are messed up, c1w2.

### ISSUE THREAD

**Issue by ma-habibi** [greyhatguy007/Machine-Learning-Specialization-Coursera#29]
in the optional labs 02 and 03 of week2 of course1, there is a notation table, the markdown looked messed up ( took the screen shots in the jupyter lab using brave browser ):

 ### lab02 : 
<img width="1013" alt="c1w2lab02" src="https://github.com/greyhatguy007/Machine-Learning-Specialization-Coursera/assets/106245122/9bbb653c-3d7b-435e-9178-3bce32a8849e">

### lab03 : 
<img width="1009" alt="c1w2lab03" src="https://github.com/greyhatguy007/Machine-Learning-Specialization-Coursera/assets/106245122/4354ab6a-f9ed-4b4a-a43e-982f106d2cd3">

i used the github WEB UI editor,  as a refrence and fixed the table.
<img width="858" alt="ref" src="https://github.com/greyhatguy007/Machine-Learning-Specialization-Coursera/assets/106245122/93101bd9-9164-4802-bce9-b8c9c02b2922">

Let me now if i can submit a pull req.
thanks.

**Comment by 19007361** [comment]
Also, for the 3rd last codeblock, where it states

` w = w - alpha * dj_dw`

shouldn't this be

` w = w - np.dot(alpha,dj_dw)`

? Otherwise, it tries to multiply a float with a list

**Comment by greyhatguy007** [comment]
Resolved in PR #31
