### ISSUE TITLE
ML course C1-W2 1st Programming Assignment

### ISSUE THREAD

**Issue by Ronny1999** [greyhatguy007/Machine-Learning-Specialization-Coursera#3]
Hey there…@greyhatguy007  In ML C1 W2 1St Programming assignment I keep getting below errors. Can you help me out!
Please note that I am not too familiar with Jupyter notebook.
Here’s Images of 
![ML-C1W2 ASGNMT2](https://user-images.githubusercontent.com/111123837/185630148-ea1bbecf-458e-448f-80bc-aa8f9f17256a.PNG)
![ML-C1W2 ASGNMT2](https://user-images.githubusercontent.com/111123837/185630242-d6ae2837-e64e-4a0d-8b61-b8b69d6c6217.PNG)

**Comment by greyhatguy007** [comment]
Did you complete and run the cell containing the **compute_gradient** function ?
```
# UNQ_C2
# GRADED FUNCTION: compute_gradient
def compute_gradient(x, y, w, b): 
    """
    Computes the gradient for linear regression 
    Args:
      x (ndarray): Shape (m,) Input to the model (Population of cities) 
      y (ndarray): Shape (m,) Label (Actual profits for the cities)
      w, b (scalar): Parameters of the model  
    Returns
      dj_dw (scalar): The gradient of the cost w.r.t. the parameters w
      dj_db (scalar): The gradient of the cost w.r.t. the parameter b     
     """
    
    # Number of training examples
    m = x.shape[0]
    
    # You need to return the following variables correctly
    dj_dw = 0
    dj_db = 0
    
    ### START CODE HERE ### 
    for i in range(m):
        f_wb = w*x[i]+b
        dj_db += f_wb - y[i]
        dj_dw += (f_wb - y[i])*x[i]
    dj_dw /= m
    dj_db /= m
    
    ### END CODE HERE ### 
        
    return dj_dw, dj_db
```

Try running this in the cell above the implementation of **compute_gradient** and make sure you've run all the cells above it correctly.

**Comment by Ronny1999** [comment]
I tried ur suggestion and still getting error.
It says “syntax eroor:invalid syntax”

In the  exercise 1 where it says public tests,what does that mean?are we
supposed to enter test case there?

**Comment by greyhatguy007** [comment]
Test cases are determined by the notebook itself. As you told that you're getting syntax errors, I'm assuming that you know how to solve them. If not, try doing a refresher in python and continue this course.

**Comment by Ronny1999** [comment]
Thank you for the clarification.

**Comment by greyhatguy007** [comment]
Anytime ! 😄💪
