### ISSUE TITLE
Comment line with index: `UNQ_C1` wasn't found in code

### ISSUE THREAD

**Issue by Saranga99** [greyhatguy007/Machine-Learning-Specialization-Coursera#37]
![Screenshot 2023-11-04 023233](https://github.com/greyhatguy007/Machine-Learning-Specialization-Coursera/assets/65158515/ccc91a02-9eef-41ef-9f6c-661ecca718a2)

**Comment by hubertdomagalaa** [comment]
I have the same issue man

**Comment by Harshhiiit** [comment]
bro is your issue get resolve? same problem occured with me too .

**Comment by AnitSarkar123** [comment]
same problem also for me
