### ISSUE TITLE
Found a typo

### ISSUE THREAD

**Issue by bear743** [greyhatguy007/Machine-Learning-Specialization-Coursera#50]
**Describe the Error**
In the practice lab: 
C1 - Supervised Machine Learning - Regression and Classification\week3\C1W3A1\C1_W3_Logistic_Regression.ipynb
In section: 2.6 Learning parameters using gradient descent.

**Screenshots**
![image](https://github.com/user-attachments/assets/bcb53bbf-f39c-4ca1-b16c-b40a69365145)

**Comment by greyhatguy007** [comment]
resolved in commit 1a6b6fc2851e6ab2d44f86b84db316a82a70e494
