### ISSUE TITLE
week 3 logistic regression

### ISSUE THREAD

**Issue by Devansh-Agarwal16** [greyhatguy007/Machine-Learning-Specialization-Coursera#8]
in supervised learning week3 logistic regresssion lab assignment is not correct when i copied all exercise code and submit assignment it is showing error

**Comment by greyhatguy007** [comment]
Do not blindly copy paste the codes. This repository is just for reference. Your numpy seed might be different. Learn and understand what the code does and the logic behind it. Try to debug it yourself and learn.
